services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql
    hostname: mysql.hibit
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql8/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql  # Named volume for persistent storage
 
  redis:
    image: redis:7.4.1
    container_name: redis
    hostname: redis.hibit
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-7.4.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data  # Optional: named volume for Redis data persistence
 
volumes:
  mysql_data:
    name: mysql_data
  redis_data:
    name: redis_data
